-- 001_init.sql
-- Initial schema for BiletFlow. Columns follow the JSON shapes in docs/api.md.
-- Where the doc says nothing, the choice is marked with a "doc is silent" comment
-- so it is easy to find the guesses later and argue about them.
--
-- Conventions used everywhere in this file:
--   * primary keys are UUID, generated by gen_random_uuid() (built into Postgres 13+,
--     no pgcrypto extension needed on Postgres 16)
--   * created_at / updated_at are timestamptz, so we store real instants and not
--     "whatever the server's clock zone was"
--   * money is INTEGER tiyn (1 KZT = 100 tiyn), never a float. INTEGER tops out at
--     about 21.4 million KZT, which is far above any single order we expect.
--   * statuses are TEXT with a CHECK constraint instead of a Postgres ENUM, because
--     adding a value to a CHECK is one migration and adding one to an ENUM is a mess.

-- Keeps updated_at honest without every query having to remember it.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email         TEXT NOT NULL UNIQUE,
  -- Auth is not built yet (teammate's task). The column exists so the register
  -- endpoint has somewhere to put a bcrypt/argon2 hash. Never store raw passwords.
  password_hash TEXT NOT NULL,
  name          TEXT NOT NULL,
  role          TEXT NOT NULL DEFAULT 'attendee'
                CHECK (role IN ('attendee', 'organizer', 'event_admin', 'platform_admin')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Doc is silent: emails are compared lower-cased in the app, and this index makes
-- "find user by email" during login a single index lookup.
CREATE UNIQUE INDEX users_email_lower_idx ON users (lower(email));

CREATE TRIGGER users_set_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- events
-- ---------------------------------------------------------------------------
CREATE TABLE events (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- RESTRICT: deleting an organizer who still has events would orphan tickets people
  -- paid for. Deactivate the user instead.
  organizer_id    UUID NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  title           TEXT NOT NULL,
  description     TEXT NOT NULL DEFAULT '',
  venue_name      TEXT NOT NULL,
  venue_address   TEXT NOT NULL,
  starts_at       TIMESTAMPTZ NOT NULL,
  ends_at         TIMESTAMPTZ NOT NULL,
  status          TEXT NOT NULL DEFAULT 'draft'
                  CHECK (status IN ('draft', 'published', 'cancelled')),
  cover_image_url TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- Doc is silent: an event that ends before it starts is always a bug, so the
  -- database refuses it rather than trusting every future write endpoint.
  CONSTRAINT events_ends_after_starts CHECK (ends_at > starts_at)
);

CREATE INDEX events_organizer_id_idx ON events (organizer_id);
CREATE INDEX events_status_idx ON events (status);
-- The public list is "published events, soonest first", so it reads this index.
CREATE INDEX events_status_starts_at_idx ON events (status, starts_at);

CREATE TRIGGER events_set_updated_at BEFORE UPDATE ON events
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- ticket_types
-- ---------------------------------------------------------------------------
-- Note there is no quantity_available column. docs/api.md says the backend computes
-- it, and a stored counter would drift out of sync with the orders table. It is
-- derived: quantity_total minus the quantity held by pending and paid orders.
CREATE TABLE ticket_types (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- CASCADE: ticket types have no meaning without their event.
  event_id       UUID NOT NULL REFERENCES events (id) ON DELETE CASCADE,
  name           TEXT NOT NULL,
  price          INTEGER NOT NULL CHECK (price >= 0),  -- tiyn; 0 means a free ticket
  -- Doc is silent on multi-currency. Everything is KZT for now; the column exists so
  -- adding another currency later is not a schema migration under time pressure.
  currency       TEXT NOT NULL DEFAULT 'KZT',
  quantity_total INTEGER NOT NULL CHECK (quantity_total >= 0),
  sales_start_at TIMESTAMPTZ,  -- NULL means "on sale from the moment it exists"
  sales_end_at   TIMESTAMPTZ,  -- NULL means "on sale until the event starts"
  is_hidden      BOOLEAN NOT NULL DEFAULT FALSE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ticket_types_event_id_idx ON ticket_types (event_id);

CREATE TRIGGER ticket_types_set_updated_at BEFORE UPDATE ON ticket_types
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- orders
-- ---------------------------------------------------------------------------
CREATE TABLE orders (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- RESTRICT on both: an order is a financial record. It outlives interest in the
  -- user's account and it must never silently vanish with the event.
  user_id    UUID NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  event_id   UUID NOT NULL REFERENCES events (id) ON DELETE RESTRICT,
  status     TEXT NOT NULL DEFAULT 'pending'
             CHECK (status IN ('pending', 'paid', 'cancelled', 'refunded')),
  subtotal   INTEGER NOT NULL CHECK (subtotal >= 0),  -- tiyn, before discounts
  discount   INTEGER NOT NULL DEFAULT 0 CHECK (discount >= 0),
  total      INTEGER NOT NULL CHECK (total >= 0),     -- tiyn, what the user pays
  -- Pending orders hold inventory for about 10 minutes, then expire (docs/api.md).
  -- Whoever builds POST /api/orders sets this and decides how expiry is swept.
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX orders_user_id_idx ON orders (user_id);
CREATE INDEX orders_event_id_idx ON orders (event_id);
-- Used by the availability query and by whatever sweeps expired pending orders.
CREATE INDEX orders_status_expires_at_idx ON orders (status, expires_at);

CREATE TRIGGER orders_set_updated_at BEFORE UPDATE ON orders
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- order_items
-- ---------------------------------------------------------------------------
CREATE TABLE order_items (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- CASCADE: an item without its order is garbage.
  order_id       UUID NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
  -- RESTRICT: you cannot delete a ticket type somebody has ordered.
  ticket_type_id UUID NOT NULL REFERENCES ticket_types (id) ON DELETE RESTRICT,
  -- Doc is silent: name and unit_price are copied from the ticket type at order time
  -- on purpose. If the organizer renames the tier or changes the price tomorrow, the
  -- old order must still show what the buyer actually agreed to.
  name           TEXT NOT NULL,
  quantity       INTEGER NOT NULL CHECK (quantity > 0),
  unit_price     INTEGER NOT NULL CHECK (unit_price >= 0),  -- tiyn
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX order_items_order_id_idx ON order_items (order_id);
CREATE INDEX order_items_ticket_type_id_idx ON order_items (ticket_type_id);

CREATE TRIGGER order_items_set_updated_at BEFORE UPDATE ON order_items
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- tickets
-- ---------------------------------------------------------------------------
-- One row per physical admission. An order item with quantity 3 becomes 3 tickets
-- when the order is paid.
CREATE TABLE tickets (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_item_id  UUID NOT NULL REFERENCES order_items (id) ON DELETE RESTRICT,
  -- Doc is silent: event_id and ticket_type_id are also stored directly, even though
  -- they could be reached through order_item. Check-in reads a ticket thousands of
  -- times at the door and must answer "is this ticket for this event?" without joins.
  event_id       UUID NOT NULL REFERENCES events (id) ON DELETE RESTRICT,
  ticket_type_id UUID NOT NULL REFERENCES ticket_types (id) ON DELETE RESTRICT,
  -- The human-readable code printed on the ticket, for example BF-7K2M-9XQP.
  code           TEXT NOT NULL UNIQUE,
  status         TEXT NOT NULL DEFAULT 'valid'
                 CHECK (status IN ('valid', 'checked_in', 'cancelled', 'refunded')),
  attendee_name  TEXT NOT NULL,
  checked_in_at  TIMESTAMPTZ,
  -- Doc is silent: recording which staff member scanned it makes disputes at the door
  -- answerable. NULL until someone scans the ticket.
  checked_in_by  UUID REFERENCES users (id) ON DELETE SET NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- qr_payload (BF1:<ticket_id>:<hmac_signature>) is deliberately not a column. It is
-- computed from the ticket id and JWT_SECRET when a ticket is returned, so rotating
-- the secret invalidates old QR codes instead of leaving signed strings in the table.

CREATE INDEX tickets_order_item_id_idx ON tickets (order_item_id);
CREATE INDEX tickets_event_id_idx ON tickets (event_id);
CREATE INDEX tickets_ticket_type_id_idx ON tickets (ticket_type_id);
CREATE INDEX tickets_checked_in_by_idx ON tickets (checked_in_by);
CREATE INDEX tickets_event_id_status_idx ON tickets (event_id, status);

CREATE TRIGGER tickets_set_updated_at BEFORE UPDATE ON tickets
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
